### ISSUE TITLE
csmt settings proper settings path

### ISSUE THREAD

**Issue by ryanmusante** [acomminos/wine-pba#38]
CSMT with wine-pba is controlled through registry key HKCU/Software/Wine/Direct3D/csmt or through winecfg dialog panel? 

Is there a conflict if both are acitvated?

**Comment by Firerat** [comment]
the wincfg dialog ( which sets the dllreirect ) 

no conflict, csmt is flagged  on by default , and as far as I can tell, you can't switch it off
it is on but dosn't tell you
if you set "csmt" in hkcu...Direct3D. it will tell you it is on but it was on anyway, but at least we know now. hmm, what does it do?
`git grep -nEC5 "cs_multithreaded|Multithreaded CS"`

The DllRedirect , definatly some code there
`git grep -nC5 "STAGING_CSMT"`

anyway, yeah, tick the box in winecfg

**Comment by SveSop** [comment]
To disable CSMT i guess you have to tick OFF the "csmt" box in the winecfg staging tab + set the DWORD reg-key for Direct3D/csmt to "0" (since the value is default "1" if unset). 
Atleast when doing that, there is a fps change that would indicate "disabled".

There should be no need to explicitly set csmt value to "1" in registry, although i have not looked enough at the staging code to check if the "default enabled" behavior is changed.

**Comment by ryanmusante** [comment]
OK, I will enable by ticking the box. It is preferable over changing registry for every wine prefix I have installed.

**Comment by goldpaw** [comment]
Did some minor tests on this, and it seems to me that the csmt box in the winecfg staging tab has no effect anymore. Ticked it on and off, and it gave no visible change in framerate, nor did it add or remove any registry keys as far as I could tell. 

When I manually added the HKCU...Direct3D/csmt and set it to 0 however, my framerate dropped like a rock! So that's the way to disable it, for those that wish to do so. The box in the staging tab simply isn't updated to work with the current 3.3 versions of wine yet. 

I'm running an AMD FX6300 CPU and AMD RX480 GPU, just to have that said. Kind of challenging for me to wrap my head around the concept that CSMT is a good thing for me now, and not just another "only for nvidia" option. But that's off-topic. Just wanted to add my 2 cents about the CSMT box in the winecfg window, and how it clearly has no effect anymore! 

Confirmed.

**Comment by IngeniousDox** [comment]
@goldpaw Disabling CSMT in Staging does have an effect. It disables the implementation of CSMT in Staging. However, since 3.3, Wine vanilla CSMT is turned on by default (before it was just off). So disabling CSMT for staging, just switched over to Vanilla CSMT. Which you then turned off with the DWORD.

But, if you had Vanilla CSMT turned off already with the DWORD. You should see a difference when enabling / disabling Staging CSMT.

**Comment by SveSop** [comment]
@goldpaw The staging CSMT setting is under HKCU/Software/Wine/DllRedirects , and not Direct3D.

It redirects wined3d.dll -> wined3d-csmt.dll.

Disabling the "staging" csmt may not mean much as it is on by default. Not sure what would happen if you add the csmt DWORD=0, and still enable the staging csmt tho.

**Comment by goldpaw** [comment]
Yeah, I should have been clearer about my using wine-staging 3.3. 

I also always create fresh wine prefixes each time I install a new wine version, so I never have any old settings that are carried over, which I'm guessing quite a few other users have. I've just found things work so much more as intended when I get rid of the old before installing something new. The Blizzard App as an example had tons of bugs when attempting to just continue running it in its old prefix with the new wine-staging-pba versions, but when I reset the prefix, everything worked like a charm straight out of the box. I set the windows version to 10 with winetricks, but didn't need to install any additional dlls as the case always were with 2.21 staging. 

And @SveSop thanks for redirecting me (pun intended) to the correct registry path. ;)

**Comment by goldpaw** [comment]
@IngeniousDox what I meant was that the switch to toggle CSMT in the winecfg staging tab has no effect for me. When manually disabling CSMT by adding the aforementioned dword in the registry, I did see a difference. A huge framerate drop, we're talking 20-30 lower fps for me from that alone. So I'm sticking with CSMT. 

But the checkbox in winecfg made no difference no matter what I tried.

**Comment by IngeniousDox** [comment]
Its still 2 different implementations of CSMT. They can either be on or off. If you haven't disabled CSMT in vanilla wine with the DWORD, and you are toggling the staging CSMT in WineCFG, you are just switching between the 2 (almost similar by now) implementations so you won't see any difference.

What you should do, is set the DWORD to 0. Then toggle the CSMT in Winecfg on and off and see if you have fps difference.

**Comment by ryanmusante** [comment]
Now that CSMT is enabled by default, issue solved.

**Comment by SveSop** [comment]
Yes, this has been fixed in wine-staging. See also pull-requests on wine-staging for additional info.
